variable "VOLT_API_URL" {}
variable "VOLT_API_P12_FILE" {}
variable "VOLT_API_CERT" {}
variable "VOLT_API_KEY" {}
variable "VES_P12_PASSWORD" {}
variable "namespace" {}
variable "projectName" {}
variable "projectPrefix" {}
#variable "tags" {}
variable "sshPublicKey" {}
variable "sshPublicKeyPath" {}
variable "sitename" {}
variable "tenant" {}
variable "nodenames" {}
variable "sitelatitude" {}
variable "sitelongitude" {}
variable "cluster_size" {}
