variable "namespace" {}
variable "projectName" {}
variable "projectPrefix" {}
variable "url" {}
variable "VOLT_API_P12_FILE" {}
#variable "tags" {}
variable "sshPublicKey" {}
variable "sshPublicKeyPath" {}
variable "sitename" {}
variable "tenant" {}
variable "nodenames" {}
variable "sitelatitude" {}
variable "sitelongitude" {}
variable "cluster_size" {}
