variable "VOLT_API_P12_FILE" {}
variable "VOLT_API_CERT" {}
variable "VOLT_API_KEY" {}
variable "VES_P12_PASSWORD" {}
variable "namespace" {}
variable "projectName" {}
variable "projectPrefix" {}
variable "clustername" {}
variable "tenant" {}
variable "hostnames" {}
variable "latitude" {}
variable "longitude" {}
variable "token" {}
